# Generated by Django 3.0.2 on 2020-01-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adventure', models.BooleanField(default=False)),
                ('children', models.BooleanField(default=False)),
                ('fantasy', models.BooleanField(default=False)),
                ('comedy', models.BooleanField(default=False)),
                ('thriller', models.BooleanField(default=False)),
                ('romance', models.BooleanField(default=False)),
                ('action', models.BooleanField(default=False)),
                ('horror', models.BooleanField(default=False)),
                ('animation', models.BooleanField(default=False)),
                ('crime', models.BooleanField(default=False)),
            ],
        ),
    ]
