# Generated by Django 3.0.2 on 2020-01-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_genre_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='email',
        ),
    ]
