# Generated by Django 3.0.2 on 2020-01-19 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_genre_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='email',
        ),
        migrations.RemoveField(
            model_name='search',
            name='name',
        ),
    ]
